//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.10 at 11:59:53 AM CAT 
//


package za.co.logoinstructor.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * At least one of move or turn required. Could be both
 * 
 * <p>Java class for Actions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Actions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="action" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="move" type="{}moveType"/>
 *                   &lt;element name="turn" type="{}turnType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Actions", propOrder = {
    "action"
})
public class Actions {

    @XmlElement(required = true)
    protected List<Actions.Action> action;

    /**
     * Gets the value of the action property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the action property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Actions.Action }
     * 
     * 
     */
    public List<Actions.Action> getAction() {
        if (action == null) {
            action = new ArrayList<Actions.Action>();
        }
        return this.action;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="move" type="{}moveType"/>
     *         &lt;element name="turn" type="{}turnType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "move",
        "turn"
    })
    public static class Action {

        @XmlElement(required = true)
        protected MoveType move;
        @XmlElement(required = true)
        protected TurnType turn;

        /**
         * Gets the value of the move property.
         * 
         * @return
         *     possible object is
         *     {@link MoveType }
         *     
         */
        public MoveType getMove() {
            return move;
        }

        /**
         * Sets the value of the move property.
         * 
         * @param value
         *     allowed object is
         *     {@link MoveType }
         *     
         */
        public void setMove(MoveType value) {
            this.move = value;
        }

        /**
         * Gets the value of the turn property.
         * 
         * @return
         *     possible object is
         *     {@link TurnType }
         *     
         */
        public TurnType getTurn() {
            return turn;
        }

        /**
         * Sets the value of the turn property.
         * 
         * @param value
         *     allowed object is
         *     {@link TurnType }
         *     
         */
        public void setTurn(TurnType value) {
            this.turn = value;
        }

    }

}
